# -*- coding: utf-8 -*-
{
    "name": "Quan ly Tai Chinh",
    "summary": "Quan ly tai chinh: ngan sach, thu chi, lien ket tai san va nhan su",
    "description": "Module quan ly tai chinh: lap ngan sach, ghi nhan phieu thu/chi, tu dong tao phieu khi bao tri hoan thanh hoac thanh ly duoc duyet. Tich hop Telegram Bot thong bao (Muc 3). Dashboard tong hop + Phan tich AI (Gemini).",
    "author": "Nhom CNTT-17-03-N11",
    "website": "https://github.com/huzgnm",
    "category": "Finance",
    "version": "0.2",
    "license": "LGPL-3",
    "depends": ["base", "mail", "nhan_su", "quan_ly_tai_san"],
    "data": [
        "security/ir.model.access.csv",
        "views/dashboard.xml",
        "views/ngan_sach.xml",
        "views/phieu_thu_chi.xml",
        "views/bao_cao_tai_chinh.xml",
        "views/khau_hao_hang_thang.xml",
        "views/ngan_sach_mua_sam.xml",
        "views/bao_cao_tai_san.xml",
        "views/telegram_config.xml",
        "views/gemini_config.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
}
