# -*- coding: utf-8 -*-
{
    "name": "Quan ly Tai San",
    "summary": "Quan ly tai san, khau hao, muon tra, bao tri, dieu chuyen",
    "description": "Module quan ly toan bo vong doi tai san: mua sam, su dung, bao tri, khau hao tu dong hang thang, dieu chuyen va thanh ly.",
    "author": "Nhom CNTT-17-03-N11",
    "website": "https://github.com/huzgnm",
    "category": "Inventory",
    "version": "0.2",
    "depends": ["base", "mail", "nhan_su", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/muon_tra.xml",
        "views/bao_tri.xml",
        "views/thanh_ly.xml",
        "views/dieu_chuyen_tai_san.xml",
        "views/tai_san.xml",
        "views/lich_su_quan_ly_tai_san.xml",
        "views/nha_cung_cap.xml",
        "views/lich_su_su_dung_tai_san.xml",
        "views/danh_muc_loai_tai_san.xml",
        "views/lich_su_dieu_chuyen_tai_san.xml",
        "views/thong_ke.xml",
        "views/menu.xml",
    ],
    "license": "LGPL-3",
}
